#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : recordproto
Version  : 1.14.2
Release  : 8
URL      : http://xorg.freedesktop.org/releases/individual/proto/recordproto-1.14.2.tar.bz2
Source0  : http://xorg.freedesktop.org/releases/individual/proto/recordproto-1.14.2.tar.bz2
Summary  : Record extension headers
Group    : Development/Tools
License  : HPND
Requires: recordproto-doc
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : xmlto

%description
X Record Extension
This extension defines a protocol for the recording and playback of user
actions in the X Window System.

%package dev
Summary: dev components for the recordproto package.
Group: Development
Provides: recordproto-devel

%description dev
dev components for the recordproto package.


%package doc
Summary: doc components for the recordproto package.
Group: Documentation

%description doc
doc components for the recordproto package.


%prep
%setup -q -n recordproto-1.14.2

%build
export LANG=C
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/extensions/recordconst.h
/usr/include/X11/extensions/recordproto.h
/usr/include/X11/extensions/recordstr.h
/usr/lib64/pkgconfig/recordproto.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/recordproto/*
